server:
  port: 8081
spring:
  datasource:
    username: root
    password: ml319xhr
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student_status?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
mybatis:
  type-aliases-package: online.xuqian.xuqian.pojo
  mapper-locations: classpath:mybatis/mapperxml/*.xml